import type { Product, ProductType, Size } from './types'

const sizesAll: Size[] = ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'L-XL']
const sizesCore: Size[] = ['XS', 'S', 'M', 'L']

export const PRODUCT_TYPES: ProductType[] = [
  'Accessories',
  'Cap',
  'Flares',
  'Hoodies',
  'Jackets',
  'Leggings',
  'Lifting Belt',
  'Shorts',
  'Tops',
]

export const PRODUCTS: Product[] = [
  {
    id: 'w-legging-daily-black',
    category: 'Women',
    type: 'Leggings',
    name: 'DAILY LEGGING',
    subtitle: 'Leggings for Every Day',
    price: 59,
    color: { name: 'Black', hex: '#111827' },
    sizes: sizesAll,
    imageHue: 215,
  },
  {
    id: 'w-bra-vuori-mint',
    category: 'Women',
    type: 'Tops',
    name: 'VUORI ALLTHEFEELS™ BRA',
    subtitle: 'Blissful Everyday Support',
    price: 49,
    color: { name: 'Mint', hex: '#7dd3c7' },
    sizes: sizesCore,
    imageHue: 155,
  },
  {
    id: 'w-shorts-runner-black',
    category: 'Women',
    type: 'Shorts',
    name: 'LIGHTWEIGHT RUN SHORT',
    subtitle: 'Soft. Strong. Sustainable.',
    price: 59,
    color: { name: 'Black', hex: '#0f172a' },
    sizes: sizesCore,
    imageHue: 230,
  },
  {
    id: 'w-top-energy-navy',
    category: 'Women',
    type: 'Tops',
    name: 'ENERGY TOP LONG',
    subtitle: 'Soft Performance Stretch',
    price: 55,
    color: { name: 'Navy', hex: '#1e3a8a' },
    sizes: sizesCore,
    imageHue: 210,
  },
  {
    id: 'w-legging-daily-graphite',
    category: 'Women',
    type: 'Leggings',
    name: 'DAILY LEGGING',
    subtitle: 'Leggings for Every Day',
    price: 59,
    color: { name: 'Graphite', hex: '#4b5563' },
    sizes: sizesAll,
    imageHue: 195,
  },
  {
    id: 'w-bra-vuori-sky',
    category: 'Women',
    type: 'Tops',
    name: 'VUORI ALLTHEFEELS™ BRA',
    subtitle: 'Blissful Everyday Support',
    price: 49,
    color: { name: 'Sky', hex: '#93c5fd' },
    sizes: sizesCore,
    imageHue: 200,
  },
  {
    id: 'w-hoodie-cloud-cream',
    category: 'Women',
    type: 'Hoodies',
    name: 'CLOUD HOODIE',
    subtitle: 'Warmth with Breathability',
    price: 89,
    color: { name: 'Cream', hex: '#f3f4f6' },
    sizes: sizesCore,
    imageHue: 40,
  },
  {
    id: 'w-jacket-windbreaker-sand',
    category: 'Women',
    type: 'Jackets',
    name: 'EVERYDAY WINDBREAKER',
    subtitle: 'Lightweight Layering',
    price: 119,
    color: { name: 'Sand', hex: '#e7d3b0' },
    sizes: sizesCore,
    imageHue: 55,
  },
  {
    id: 'w-cap-classic-white',
    category: 'Women',
    type: 'Cap',
    name: 'CLASSIC CAP',
    subtitle: 'One Size, All Day',
    price: 25,
    color: { name: 'White', hex: '#ffffff' },
    sizes: ['M'],
    imageHue: 15,
  },
  {
    id: 'w-accessory-tote',
    category: 'Accessories',
    type: 'Accessories',
    name: 'ESSENTIAL TOTE',
    subtitle: 'Carry Everything',
    price: 39,
    color: { name: 'Stone', hex: '#e5e7eb' },
    sizes: ['M'],
    imageHue: 25,
  },
  {
    id: 'w-belt-lifting',
    category: 'Accessories',
    type: 'Lifting Belt',
    name: 'LIFTING BELT',
    subtitle: 'Support for Heavy Days',
    price: 69,
    color: { name: 'Black', hex: '#111827' },
    sizes: ['S', 'M', 'L'],
    imageHue: 215,
  },
  {
    id: 'w-flares-soft-gray',
    category: 'Women',
    type: 'Flares',
    name: 'SOFT FLARE PANT',
    subtitle: 'From Studio to Street',
    price: 79,
    color: { name: 'Heather', hex: '#d1d5db' },
    sizes: sizesAll,
    imageHue: 20,
  },
]

